import { useEffect, useRef, useState } from 'react';
import { api, write } from '../client-api';
import type { Bootstrap } from '../shared/types';
import type { AutomationOverview, HistoryPage, SavedItem, SearchHit } from '../shared/discovery';
import { AgentExchange, isAgentExchange } from "./AgentExchange";
import { ActionReceipt } from "./ActionReceipt";
import { MessageMarkdown } from './MessageMarkdown';
import { When } from './When';
export function DiscoveryPanel({ bootstrap, onRoutine }: { bootstrap: Bootstrap; onRoutine: (botId:string,routineId:string,resultId?:string)=>void }) {
  const generation=useRef(0);
  const [tab,setTab] = useState<'search'|'saved'|'automations'>('search');
  const [query,setQuery] = useState(''); const [hits,setHits] = useState<SearchHit[]>([]); const [saved,setSaved] = useState<SavedItem[]>([]);
  const [overview,setOverview] = useState<AutomationOverview|null>(null); const [page,setPage] = useState<HistoryPage|null>(null);
  const [error,setError] = useState(''); const [busy,setBusy] = useState(false); const [savedMessage,setSavedMessage]=useState<string|undefined>();
  const [notice,setNotice] = useState('');
  async function run(work:()=>Promise<void>) { const scope=generation.current;setBusy(true);setError('');setNotice('');try {await work();}catch(e){if(scope===generation.current)setError((e as Error).message);}finally{if(scope===generation.current)setBusy(false);} }
  function changeTab(next:typeof tab) { generation.current++;setPage(null);setError('');setNotice('');setBusy(false);setTab(next); }
  useEffect(()=> { setPage(null); void run(async()=> { if(tab==='saved') setSaved(await api('/saved')); if(tab==='automations') setOverview(await api('/automations')); }); },[tab,bootstrap.user.id]);
  async function history(botId:string,sessionId:string,offset=0,messageId?:string) { const scope=generation.current;await run(async()=> { const value=await api<HistoryPage>(`/bots/${encodeURIComponent(botId)}/history/${encodeURIComponent(sessionId)}?offset=${offset}`);if(scope!==generation.current)return;if(messageId&&!value.messages.some(message=>message.id===messageId))throw new Error('This saved reply is unavailable. Its original history changed in Hermes.');setSavedMessage(messageId);setPage(value); }); }
  async function pin(item:Omit<SavedItem,'id'|'createdAt'>) { await run(async()=> {await write('/saved',item);setNotice('Saved. Find it in Saved items.');}); }
  return <div className="discovery-panel"><nav className="view-tabs" aria-label="Search and saved"><button aria-pressed={tab==='search'} onClick={()=>changeTab('search')}>Search</button><button aria-pressed={tab==='saved'} onClick={()=>changeTab('saved')}>Saved items</button><button aria-pressed={tab==='automations'} onClick={()=>changeTab('automations')}>Automations</button></nav>
    {error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Loading...</p>}
    {page ? <section><button className="discovery-back" onClick={()=>setPage(null)}>‹ Back to results</button><h2>Conversation history</h2><p className="muted">Read from Hermes. This view does not change the assistant’s active conversation.</p>
      <button disabled={busy} onClick={()=>void pin({kind:'session',botId:page.botId,sessionId:page.sessionId,title:hits.find(hit=>hit.sessionId===page.sessionId)?.title.slice(0,120)||'Saved conversation'})}>Save conversation</button>
      {page.messages.map(message=><article className="history-message" id={`history-${message.id}`} key={message.id} style={savedMessage===message.id?{borderLeft:"3px solid var(--accent)",paddingLeft:12}:undefined}><small>{message.role}</small>{message.role==='assistant'&&<button disabled={busy} onClick={()=>void pin({kind:"session",botId:page.botId,sessionId:page.sessionId,messageId:message.id,offset:page.offset,title:message.text.replace(/[#*_`]/g," ").trim().slice(0,120)||"Saved reply"})}>Save reply</button>}<>{isAgentExchange(message)?<AgentExchange message={message} recipient={bootstrap.bots.find(bot=>bot.id===page.botId)?.name||"Assistant"}/>:message.toolCall?<ActionReceipt call={message.toolCall}/>:<MessageMarkdown text={message.text}/>}</>{message.files?.map(file=><a key={file.id} href={`/api/files/${encodeURIComponent(file.id)}`} target="_blank" rel="noreferrer">{file.name}</a>)}</article>)}
      <div className="discovery-actions"><button disabled={busy||page.offset===0} onClick={()=>void history(page.botId,page.sessionId,Math.max(0,page.offset-100))}>Previous page</button><button disabled={busy||!page.hasMore} onClick={()=>void history(page.botId,page.sessionId,page.offset+100)}>Next page</button></div></section> : <>
    {tab==='search'&&<><form className="discovery-search" onSubmit={event=>{event.preventDefault();void run(async()=>{const result=await api<{hits:SearchHit[];unavailableBots:string[]}>(`/search?q=${encodeURIComponent(query.trim())}`);setHits(result.hits);setNotice(result.unavailableBots.length?`Could not search ${result.unavailableBots.length} assistant(s).`:result.hits.length?'':'No matching conversations.');});}}><input aria-label="Search conversations" placeholder="Answers, files, or a topic" maxLength={200} value={query} onChange={event=>setQuery(event.target.value)}/><button disabled={busy||!query.trim()}>Search</button></form><p className="muted discovery-hint">Searches answers, attachment names and routine previews across your assistants.</p>
      {hits.map(hit=><button className="today-row" key={`${hit.botId}:${hit.sessionId}`} onClick={()=>hit.routineId?onRoutine(hit.botId,hit.routineId,hit.resultId):void history(hit.botId,hit.sessionId)}><span className="today-row-copy"><strong>{hit.title}</strong><small>{hit.botName}</small><small>{hit.snippet.replace(/<[^>]*>/g,'').slice(0,300)}</small></span><span aria-hidden="true">›</span></button>)}</>}
    {tab==='saved'&&<><p className="muted discovery-hint">Links to original conversations and routine outputs. Removed originals may be unavailable.</p>{!saved.length&&<p className="discovery-empty">No saved items yet. Save a conversation from search or an output from routine results.</p>}{saved.map(item=><div className="saved-row" key={item.id}><button className="today-row" onClick={()=>item.kind==='session'?void history(item.botId,item.sessionId!,item.offset||0,item.messageId):onRoutine(item.botId,item.routineId!,item.resultId)}><span className="today-row-copy"><strong>{item.title}</strong><small>{bootstrap.bots.find(bot=>bot.id===item.botId)?.name} · {item.kind==='routine'?'Routine output':'Conversation'}</small></span></button><button aria-label={`Remove ${item.title}`} onClick={()=>void run(async()=>{await write(`/saved/${encodeURIComponent(item.id)}`,undefined,'DELETE');setSaved(saved.filter(row=>row.id!==item.id));})}>Remove</button></div>)}</>}
    {tab==='automations'&&<><div className="discovery-toolbar"><p className="muted discovery-hint">Upcoming work, recent failures and who receives results.</p><button disabled={busy} onClick={()=>void run(async()=>setOverview(await api('/automations')))}>Refresh</button></div>{overview?.routines.map(row=><article className="automation-row" key={row.id}><h3>{row.name}</h3><p>{bootstrap.bots.find(bot=>bot.id===row.botId)?.name} · {row.enabled?'Enabled':'Paused'}</p><p>{row.nextRunAt&&row.enabled?<>Next: <When value={row.nextRunAt} /></>:'No upcoming run reported'}{row.lastStatus&&` · Last result: ${row.lastStatus}`}</p>{(row.lastError||row.lastDeliveryError)&&<p role="status" className="form-error">{row.lastError||row.lastDeliveryError}</p>}<p>Notify: {row.recipientIds?.map(id=>bootstrap.household.find(user=>user.id===id)?.name||'Household member').join(', ')||'No routine recipients selected'}</p><div className="discovery-actions"><button onClick={()=>onRoutine(row.botId,row.id)}>View outputs</button><button disabled={busy} onClick={()=>void run(async()=>{await write(`/routines/${encodeURIComponent(row.id)}/state`,{enabled:!row.enabled},'PATCH');setOverview(await api('/automations'));})}>{row.enabled?'Pause':'Resume'}</button></div></article>)}{overview&&!overview.routines.length&&<p className="discovery-empty">No routines yet. Create one in assistant settings.</p>}
      <h3>Usage over 30 days</h3><p className="muted">Recorded main-session usage. Estimates and provider invoices may differ. Auxiliary calls are not included.</p>{overview?.usage.map(usage=><article className="automation-row" key={usage.botId}><strong>{bootstrap.bots.find(bot=>bot.id===usage.botId)?.name}</strong><p>{usage.sessions} sessions · {usage.inputTokens.toLocaleString()} input / {usage.outputTokens.toLocaleString()} output tokens</p><p>Reported cost: {usage.actualCost===null?'Unknown':`$${usage.actualCost.toFixed(2)}${usage.partial?' (partial)':''}`} · Estimate: {usage.estimatedCost===null?'Unknown':`$${usage.estimatedCost.toFixed(2)}`}</p></article>)}{!!overview?.unavailableBots.length&&<p role="status">Usage unavailable for {overview.unavailableBots.length} assistant(s).</p>}</>}
    </>}
  </div>;
}
